/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_haocai_bsdiff_BsDiff */

#ifndef _Included_com_haocai_bsdiff_BsDiff
#define _Included_com_haocai_bsdiff_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haocai_bsdiff_BsDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_haocai_bsdiff_BsDiff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
